# Generated by Django 4.2.4 on 2023-08-27 09:53

from django.db import migrations
from pathlib import Path


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.RunSQL(
            Path("sql/seed_store.sql").read_text(),
            Path("sql/reverse_seed_store.sql").read_text(),
        )
    ]
