# Generated by Django 4.2.4 on 2023-08-11 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_alter_customer_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={"permissions": [("cancel_order", "Can cancel order")]},
        ),
    ]
