# Generated by Django 4.2.4 on 2023-08-06 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_alter_product_promotions"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(
                fields=["first_name", "last_name"],
                name="store_custo_first_n_8f83e0_idx",
            ),
        ),
    ]
