# Generated by Django 4.2.4 on 2023-08-06 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_customer_store_custo_first_n_8f83e0_idx"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="price",
            new_name="unit_price",
        ),
    ]
