# Generated by Django 4.2.4 on 2023-08-06 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0005_rename_price_product_unit_price"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="last_updated",
            new_name="last_update",
        ),
    ]
