# Generated by Django 4.2.4 on 2023-08-06 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0006_rename_last_updated_product_last_update"),
    ]

    operations = [
        migrations.RenameField(
            model_name="orderitem",
            old_name="price",
            new_name="unit_price",
        ),
    ]
