services:
  # nginx

  backend:
    build:
      context: .
      dockerfile: Dockerfile.prod
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - database
      - redis
      - maildev
    environment:
      - SECRET_KEY=topsecretvalue
      - DATABASE_URL=postgres://postgres:mysecretpassword@database:5432/storefront
      - CACHE_URL=redis://redis:6379
      - CELERY_BROKER_URL=redis://redis:6379
      - CELERY_RESULT_BACKEND_URL=redis://redis:6379
      - EMAIL_URL=smtp://maildev:1080
      - LOG_LEVEL=DEBUG
    volumes:
      - django-logs:/app/general.log

  celery-worker:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: celery -A storefront worker -l INFO
    restart: always
    depends_on:
      - redis
    environment:
      - SECRET_KEY=topsecretvalue
      - DATABASE_URL=postgres://postgres:mysecretpassword@database:5432/storefront
      - CACHE_URL=redis://redis:6379
      - CELERY_BROKER_URL=redis://redis:6379
      - CELERY_RESULT_BACKEND_URL=redis://redis:6379
      - EMAIL_URL=smtp://maildev:1080

  celery-beat:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: celery -A storefront beat -l INFO
    restart: always
    depends_on:
      - redis
      - celery-worker
    environment:
      - SECRET_KEY=topsecretvalue
      - DATABASE_URL=postgres://postgres:mysecretpassword@database:5432/storefront
      - CACHE_URL=redis://redis:6379
      - CELERY_BROKER_URL=redis://redis:6379
      - CELERY_RESULT_BACKEND_URL=redis://redis:6379
      - EMAIL_URL=smtp://maildev:1080

  maildev:
    image: maildev/maildev
    ports:
      - "5000:1080"
    restart: always

  database:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_DB: storefront
      POSTGRES_PASSWORD: mysecretpassword
    volumes:
      - db-data:/var/lib/postgresql/data

  redis:
    image: redis:7.2-alpine
    command: redis-server --save 60 1
    ports:
      - "6379:6379"
    restart: always
    volumes:
      - redis-data:/data

volumes:
  django-logs:
  db-data:
  redis-data:
