services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - database
      - redis
    develop:
      watch:
        - action: sync
          path: ./
          target: /app/
          ignore:
            - .venv/
        - action: rebuild
          path: pyproject.toml

  database:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_DB: storefront
      POSTGRES_PASSWORD: mysecretpassword
    volumes:
      - db-data:/var/lib/postgresql/data

  redis:
    image: redis:7.2-alpine
    ports:
      - "6379:6379"
    restart: always
    volumes:
      - redis-data:/data

volumes:
  db-data:
  redis-data:
