version: "3.8"

services:

  backend:
    build: .
    ports:
      - "8000:8000"
    restart: on-failure
    environment:
      - DB_HOST=db
    depends_on:
      - db
      - redis
    volumes:
      - .:/backend

  celery:
    build: .
    command: celery -A storefront worker --loglevel=info
    restart: always
    depends_on:
      - db
      - redis
    volumes:
      - .:/backend

  celery-beat:
    build: .
    command: celery -A storefront beat --loglevel=info
    restart: always
    depends_on:
      - db
      - redis
    volumes:
      - .:/backend

  flower:
    build: .
    ports:
      - "5555:5555"
    command: celery -A storefront flower
    restart: always
    depends_on:
      - backend
      - db
      - redis
      - celery
      - celery-beat
    environment:
      - DEBUG=1
      - CELERY_BROKER=redis://redis:6379
      - CELERY_BACKEND=redis://redis:6379

  db:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: storefront
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7.2-alpine
    ports:
      - "6379:6379"
    restart: always
    volumes:
      - redisdata:/data

volumes:
  pgdata:
  redisdata:
