# Generated by Django 5.0.7 on 2024-07-24 10:32

import file_validator.models
import imagekit.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=imagekit.models.fields.ProcessedImageField(
                upload_to="products/images",
                validators=[
                    file_validator.models.FileSizeValidator(
                        max_upload_file_size=5242880
                    )
                ],
            ),
        ),
    ]
