# Generated by Django 5.0.7 on 2024-07-29 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collection",
            name="title",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
